## Balance and Unbalanced Data

In [ ]:
import pandas as pd

In [ ]:
# Load the dataset (Assuming the file is named 'creditcard.csv')
df = pd.read_csv(r"C:\Users\svikr\Downloads\creditcard.csv")

In [ ]:
# Display the first few rows of the dataframe
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [ ]:
# Check the distribution of the target variable (Assuming it's named 'Class')
print(df['Class'].value_counts())

Class
0    284315
1       492
Name: count, dtype: int64

## 1st Methode

In [ ]:
from sklearn.utils import resample

In [ ]:
# Separate majority and minority classes
df_majority = df[df.Class == 0]
df_minority = df[df.Class == 1]

In [ ]:
# Downsample majority class
df_majority_downsampled = resample(df_majority,
                                  replace=False,    # sample without replacement
                                  n_samples=len(df_minority),  # to match minority class
                                  random_state=42) # reproducible results

In [ ]:
# Combine minority class with downsampled majority class
df_balanced = pd.concat([df_majority_downsampled, df_minority])

In [ ]:
# Display new class counts
print(df_balanced.Class.value_counts())

Class
0    492
1    492
Name: count, dtype: int64

## 2nd Methode

In [ ]:
df_majority.sample(492)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
61432,49834.0,-0.144109,-0.423228,1.843110,-1.496684,-1.335167,0.147811,-0.432152,0.108974,-2.860966,...,-0.120383,-0.039556,0.260981,0.184967,-0.765808,-0.342611,0.187320,0.149778,70.65,0
141655,84455.0,-0.980848,-0.296213,0.135269,-1.613083,-0.533642,0.016099,1.060270,0.090428,1.215303,...,0.016057,0.307298,0.043099,-0.410496,0.149757,-0.788706,0.299549,0.035458,282.40,0
96929,66009.0,0.857401,-0.964242,0.821355,0.132100,-0.968180,0.644248,-0.660244,0.338657,0.991409,...,-0.088310,-0.349849,-0.072198,-0.221700,0.012026,0.959676,-0.051867,0.023087,159.10,0
134343,80761.0,1.096567,0.169603,0.515852,1.328184,-0.168266,0.030413,0.001528,0.096092,-0.035383,...,-0.029179,0.119934,-0.058978,0.241933,0.615088,-0.344055,0.037597,0.009533,14.08,0
277616,167753.0,-0.933863,0.991443,-0.546024,-0.459216,1.240146,-0.085280,1.189180,0.253405,-1.550828,...,0.147659,0.091320,-0.547253,-1.383827,1.056339,0.989492,-0.205854,-0.084087,72.60,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124956,77485.0,-2.109755,-0.437033,1.882686,-1.141328,0.286260,0.005740,-0.735597,0.740791,-0.129891,...,0.252863,0.620373,0.208811,-0.759331,0.418390,1.075910,-0.186850,-0.099363,13.50,0
147306,88362.0,2.135842,-0.010384,-1.480705,0.163302,0.446419,-0.596608,0.226555,-0.321908,0.470370,...,-0.346686,-0.813602,0.200273,-0.977916,-0.127914,0.257224,-0.065983,-0.068427,1.98,0
43785,41650.0,-0.677758,-0.815462,1.230302,-0.537248,0.097823,-0.010984,-0.425611,0.276235,-1.251343,...,0.299076,0.633702,0.052906,-0.300379,-0.177606,-0.038967,0.113386,0.132758,66.44,0
284702,172696.0,-0.481672,1.579297,-1.284154,-0.083524,0.097815,-1.421216,0.265490,0.528140,-0.307906,...,0.388981,0.931019,-0.114448,-0.196205,-0.350532,-0.156168,-0.242231,-0.000290,2.32,0
116084,74137.0,-2.396330,0.098610,1.528159,3.300984,0.302657,0.101627,-0.304474,0.414286,-1.008917,...,-0.420449,-0.953742,-0.866878,-0.031749,-0.060628,0.031076,0.397456,-0.413274,97.61,0